### PR TITLE
TEIID-4437: Add more feature pack moudle

### PR DESCRIPTION
**Pull request by kylinsoong**
### Change Summary
- salesforce depend on webservice
- remove duplicated groupId definition

### CODE REVIEW

**Comment by kylinsoong** [comment]
@rareddy Could you look and merge this request, current I have some thoughts to move forward the left translator:
1. Put `translator-hbase`, `translator-hive`, `translator-prestodb`, `translator-olap` together with jdbc extension
2. Put `translator-odata`, `translator-odata4`, `translator-swagger` together with webserive extension
3. `translator-jpa` - seems jpa translator need a jpa connector which can supply EntityManagerFactory, and EntityManager, seems we lost it, how jpa translator works?
4. Skip the `sandbox` - since the translators/connectors under sandbox no longer used in final dist, so just skip it.
I would like to know your suggestions then do further work.

Kylin

**Comment by rareddy** [comment]
Kylin, please revert the "groupid" removal. That is needed, as otherwise it will change the module identity with what we had before. There is no need to keep the maven folder structure  aligned with maven groupid

**Comment by rareddy** [comment]
I moved all others except loopback, olap, jpa. create "misc" directory move these three in there. The resubmit your pull

**Comment by kylinsoong** [comment]
> Kylin, please revert the "groupid" removal. That is needed, as otherwise it will change the module identity with what we had before. There is no need to keep the maven folder structure aligned with maven groupid

I am not completely understand, since parent and the module have the same groupId `org.jboss.teiid.connectors`, and eclipse validation suggest duplicated groupId, so I remove it. 

```
<parent>
      <groupId>org.jboss.teiid.connectors</groupId>
      <artifactId>misc</artifactId>
      <version>9.1.0.Beta2-SNAPSHOT</version>
</parent>
<artifactId>translator-loopback</artifactId>
<groupId>org.jboss.teiid.connectors</groupId>
<name>Loopback Translator</name>
<description>Loopback Translator</description>
<packaging>bundle</packaging>
```

**Pull request closed without merging**
